### PR TITLE
allow tracer.get_var_name to work on pypy3

### LINKED ISSUE #141: tracer.get_var_name returns None instead of default on pypy3
on pypy3 (pypy 7.2.0-beta0),
`tracer.get_var_name` returns `None` when called through `Signal.__init__` as follows:

```python
from nmigen import Signal
v = Signal(reset_less=False)
print(v.name)
```

instead of returning `None`, it would be better to return `default` or raise an exception.

having `None` as the name causes `Simulator` to crash.

### PR DESCRIPTION
**Pull request by programmerjake**
Fixes #141

### CODE REVIEW

**Comment by whitequark** [comment]
Would you mind adding PyPy to the Travis matrix? This way we'll know if it breaks in the future.

**Comment by whitequark** [comment]
Hm:
```
RPython traceback:
  File "pypy_interpreter.c", line 37862, in BuiltinCode_funcrun_obj
  File "pypy_module__io_1.c", line 11219, in W_BufferedReader_readline_w
  File "implement_2.c", line 31859, in dispatcher_70
  File "pypy_module__io.c", line 16003, in W_BufferedReader__raw_read
Traceback (most recent call last):
  File "/home/travis/.local/bin/sby", line 388, in <module>
    retcode |= run_job(t)
  File "/home/travis/.local/bin/sby", line 346, in run_job
    job.run(setupmode)
  File "/home/travis/.local/bin/../share/yosys/python3/sby_core.py", line 634, in run
    self.taskloop()
  File "/home/travis/.local/bin/../share/yosys/python3/sby_core.py", line 251, in taskloop
    task.poll()
  File "/home/travis/.local/bin/../share/yosys/python3/sby_core.py", line 155, in poll
    outs = self.p.stdout.readline().decode("utf-8")
SystemError: unexpected internal exception (please report a bug): <BlockingIOError object at 0x7f93db82ff00>; internal traceback was dumped to stderr
```

Can you please report this to PyPy so we can ideally move PyPy back in the build matrix? In my experience allow-fail CI builds don't really account to much if anything. But it's not a blocker for merging this.

**Comment by programmerjake** [comment]
> Can you please report this to PyPy so we can ideally move PyPy back in the build matrix? In my experience allow-fail CI builds don't really account to much if anything. But it's not a blocker for merging this.

see https://bitbucket.org/pypy/pypy/issues/3042/crash-when-reading-non-blocking-subprocess

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
