### PR TITLE
lib.io: import CRG from Migen.

### PR DESCRIPTION
**Pull request by jfng**
Tests are missing.

### CODE REVIEW

**Comment by whitequark** [comment]
I am wondering if the nMigen CRG implementation should take into account FPGAs like iCE40, where the BRAMs cannot be accessed for some time after startup. (This is very poorly documented but it's a hard requirement...)

So, my CRG for iCE40 uses a timer.

**Comment by jfng** [comment]
> I am wondering if the nMigen CRG implementation should take into account FPGAs like iCE40, where the BRAMs cannot be accessed for some time after startup. (This is very poorly documented but it's a hard requirement...)

Is this what you meant ?

**Comment by whitequark** [comment]
Yes. Isn't it sufficient to use ResetInserter here?

**Comment by whitequark** [comment]
I think there is no particular need for a generic CRG in nMigen because various `vendor.*` packages use highly platform-specific reset generation and clock gating gateware which is much better at this job.

**Pull request closed without merging**
